stages:
    - compile
    - test
    - build

maven-compile:
    image: maven:3-jdk-8
    stage: compile
    script:
        - "mvn compile --settings .gitlab.settings.xml -Dmaven.test.skip"

maven-test:
    image: maven:3-jdk-8
    stage: test
    script:
        - "mvn test"


maven-build-internal:
    image: maven:3-jdk-8
    stage: build
    script:
        - "mvn package --settings .gitlab.settings.xml -P internal,evadev,dgvadev -Dmaven.test.skip"
    artifacts:
        paths:
            - eva-server/target/*war