stages:
    - build
    - deploy

variables:
    TOMCAT_USER: "$TOMCAT_INTERNAL_USER"
    TOMCAT_PASSWORD: "$TOMCAT_INTERNAL_PASSWORD"
    TOMCAT_HOST: "$TOMCAT_INTERNAL_HOST"
    MAVEN_PROFILE: "internal,evadev,dgvadev"

.maven-build:
    image: maven:3.5.4-jdk-8
    stage: build
    script:
        - "mvn package --settings .gitlab.settings.xml -P $MAVEN_PROFILE"
    artifacts:
        paths:
            - eva-server/target/eva.war

.deploy-tomcat:
    image: alpine:3.8
    stage: deploy
    environment:
        name: internal
        url: http://ves-ebi-f8:8080/eva/EVA1288/webservices/rest/swagger-ui.html
    script:
        - "apk add --update curl"
        - "curl -u $TOMCAT_USER:$TOMCAT_PASSWORD -T \"eva-server/target/eva.war\" \"http://$TOMCAT_HOST/manager/text/deploy?path=/eva/EVA1288&update=true\""

maven-build-internal:
    extends: .maven-build
    variables:
        MAVEN_PROFILE: "internal,evadev,dgvadev"

maven-build-development:
    extends: .maven-build
    variables:
        MAVEN_PROFILE: "development,evadev,dgvadev"

deploy-tomcat-internal:
    extends: .deploy-tomcat
    variables:
        TOMCAT_USER: "$TOMCAT_INTERNAL_USER"
        TOMCAT_PASSWORD: "$TOMCAT_INTERNAL_PASSWORD"
        TOMCAT_HOST: "$TOMCAT_INTERNAL_HOST"

deploy-tomcat-development:
    extends: .deploy-tomcat
    when: manual
    variables:
        TOMCAT_USER: "$TOMCAT_DEVELOPMENT_USER"
        TOMCAT_PASSWORD: "$TOMCAT_DEVELOPMENT_PASSWORD"
        TOMCAT_HOST: "$TOMCAT_DEVELOPMENT_HOST"