stages:
    - build

maven-build:
    image: maven:3-jdk-8
    stage: build
    script: 
        - "mvn install --settings .gitlab.settings.xml -Dmaven.test.skip"
    artifacts:
        paths:
            - eva-server/target/*war