stages:
    - build

cache:
    paths:
        - ".m2/repository/"

maven-build-internal:
    image: maven:3-jdk-8
    stage: build
    script:
        - "mvn package --settings .gitlab.settings.xml -P internal,evadev,dgvadev"
    artifacts:
        paths:
            - eva-server/target/eva.war